# Site settings
title: salow.co
description: Android application developer, Embedded feak,Iot geek.
keywords: Android, clash of clans,Modern, Blogging, Fun
author: Salow
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.salow.co" # the base hostname & protocol for your site
